### ISSUE TITLE
How to use water_heater.orca_water_heater in home assistant

### ISSUE THREAD

**Issue by Navaroff** [Tomasinjo/orca-energy-ha#2]
Thanks for the great work Tomas.

I´m looking for the HA lovelace frontend integration of orca water heater.
![image](https://github.com/Tomasinjo/orca-energy-ha/assets/32979269/67d8676c-b72d-4f1c-8d7e-dfb0a907a88a)

I somehow can´t have water heater in a frontend in a form of regulating water temperature. When I click on the water_heater.orca_water_heater in devices I get nice control panel (see above photo) to adjust the temperature, but I cant import it to any entities or thermostat. Can you tell me how you did it by yourself?

Hvala.

**Comment by Tomasinjo** [comment]
What do you mean by importing it to any entities?

There should be entity "water_heater.orca_water_heater" with state and attributes. If you want to change temperature in automation, then you can use services such as "service: water_heater.set_temperature"
