### ISSUE TITLE
Error on config ([%key:common::config_flow::error::cannot_connect%])

### ISSUE THREAD

**Issue by 54m5p33d** [Tomasinjo/orca-energy-ha#3]
Thanks for making the Orca HA integration available.
I am struggling with the initial setup of my system of my DUO 200 (with touch screen). 
I can access the internal IP (but there is no login options there). 
So when testing the HA integration with the suggested admin/admin I am getting [%key:common::config_flow::error::cannot_connect%]

When I try 
http://192.168.1.111/cgi/login?username=admin&password=admin

I do get the response 
1
#S_OK
IDALToken=
INFO={"g":"admin","ot":0,"ex":3950,"pwdd":3,"clientID":1}

**Comment by Tomasinjo** [comment]
I get the following response when accessing the same URL:

1
#S_OK
IDALToken=xxxxxxxxxxxxxxxxxxxxxxxxxx


It seems the default credentials work in your case, it just doesn't return the token. Is it possible they disabled administrative access in newer revisions? For how long do you have your heat pump?

**Comment by 54m5p33d** [comment]
Hey, thanks for a fast response. Maybe i was not clear, I do get the token generated (I just removed  it for the issue).

The heatpump is about 1year old

**Comment by Tomasinjo** [comment]
Got it. Can you try again and then check your home assistant logs (Settings -> System -> Logs) for anything related to orca integration? Most likely python exception.

**Comment by 54m5p33d** [comment]
[home-assistant_2024-02-27T20-45-18.851Z.log](https://github.com/Tomasinjo/orca-energy-ha/files/14425506/home-assistant_2024-02-27T20-45-18.851Z.log)

If I populate the host with just the internal IP (e.g. 192.168.1.111) I get nothing in the logs, but if I add http://192.168.1.111 the attached ERROR is generated in the logs

**Comment by timrosu** [comment]
@54m5p33d have you managed to resolve the issue? I have Mono with Carel touchscreen and have exact same situation.

**Comment by 54m5p33d** [comment]
No, i still have the same problem

**Comment by Tomasinjo** [comment]
If you want, we can hop on a zoom call and I can do some tests to better understand what is going on.

I'll be waiting in this telegram group if anyone wants do it:
https://t.me/+DrcVdoyY-dE4OGM0

**Comment by Tomasinjo** [comment]
This should now be fixed. The issue was initial connection test in config flow. Thanks to @timrosu for helping me troubleshoot.

Please report back and close the issue if fixed

**Comment by 54m5p33d** [comment]
Thanks for the update! It works.
